#!/usr/bin/env bash
# This script reads and cuts the content of /etc/passwd to display username, user ID, and home directory path for each user.

# Using a while loop to read the content of /etc/passwd line by line
while IFS=":" read -r username _ userid _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
