#!/usr/bin/env bash
# This script displays different messages for specific loop iterations using the case statement

# Initialize a counter variable
count=1

# Using a while loop to loop from 1 to 20
while [ $count -le 20 ]
do
    case $count in
        4)
            echo "$count"
            echo "bad luck from China"
            ;;
        9)
            echo "$count"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$count"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$count"
            ;;
    esac

    ((count++))
done
